### ISSUE TITLE
Crashes when using Google Maps SDK for iOS

### ISSUE THREAD

**Issue by seviu** [Appelium/AppeliumFeedback#1]
We have a problem with AppeliumFeedback 2.4.3 in which if we get the following crash when using GoogleMaps:

```
2020-12-02 17:44:48.465049+0100 homegate.ch[32932:1941756] *** Terminating app due to uncaught exception 'GMSThreadException', reason: 'The API method must be called from the main thread'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2041daf2 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2041d9d0 -[NSException initWithCoder:] + 0
	3   homegate.ch                         0x000000010c437f04 +[GMSServices sharedServicesIfActive] + 64
	4   homegate.ch                         0x000000010c42070e -[GMSMapLayer renderInContext:] + 45
	5   QuartzCore                          0x00007fff27a75111 -[CALayer _renderSublayersInContext:] + 564
	6   QuartzCore                          0x00007fff27a7308e -[CALayer renderInContext:] + 1727
	7   QuartzCore                          0x00007fff27a75111 -[CALayer _renderSublayersInContext:] + 564
	8   QuartzCore                          0x00007fff27a7308e -[CALayer renderInContext:] + 1727
	9   QuartzCore                          0x00007fff27a75111 -[CALayer _renderSublayersInContext:] + 564
	10  QuartzCore                          0x00007fff27a7308e -[CALayer renderInContext:] + 1727
	11  QuartzCore                          0x00007fff27a75111 -[CALayer _renderSublayersInContext:] + 564
	12  QuartzCore                          0x00007fff27a7308e -[CALayer renderInContext:] + 1727
	13  QuartzCore                          0x00007fff27a75111 -[CALayer _renderSublayersInContext:] + 564
	14  QuartzCore                          0x00007fff27a7308e -[CALayer renderInContext:] + 1727
	15  QuartzCore                          0x00007fff27a75111 -[CALayer _renderSublayersInContext:] + 564
	16  QuartzCore                          0x00007fff27a7308e -[CALayer renderInContext:] + 1727
	17  QuartzCore                          0x00007fff27a75111 -[CALayer _renderSublayersInContext:] + 564
	18  QuartzCore                          0x00007fff27a7308e -[CALayer renderInContext:] + 1727
	19  QuartzCore                          0x00007fff27a75111 -[CALayer _renderSublayersInContext:] + 564
	20  QuartzCore                          0x00007fff27a7308e -[CALayer renderInContext:] + 1727
	21  AppeliumFeedback                    0x000000010e2d7813 $s16AppeliumFeedback26UIScreenScreenshotProviderC16videoPixelBuffer5scaleSo11CVBufferRefa12CoreGraphics7CGFloatV_tFTf4nd_n + 851
	22  AppeliumFeedback                    0x000000010e2cbc9b $s16AppeliumFeedback14ScreenRecorderC17captureScreenshot33_E90AD91E4C426473BF4C4B96E1882D1FLLyyFyycfU_ + 139
	23  AppeliumFeedback                    0x000000010e2d78fe $sIeg_IeyB_TR + 14
	24  libdispatch.dylib                   0x000000010fb027ec _dispatch_call_block_and_release + 12
	25  libdispatch.dylib                   0x000000010fb039c8 _dispatch_client_callout + 8
	26  libdispatch.dylib                   0x000000010fb0a296 _dispatch_lane_serial_drain + 796
	27  libdispatch.dylib                   0x000000010fb0af67 _dispatch_lane_invoke + 439
	28  libdispatch.dylib                   0x000000010fb16de2 _dispatch_workloop_worker_thread + 882
	29  libsystem_pthread.dylib             0x00007fff5e73d499 _pthread_wqthread + 314
	30  libsystem_pthread.dylib             0x00007fff5e73c467 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

It is easy to reproduce: just use Appelium with any of the sample projects from GoogleMapUtils SDK:
https://github.com/googlemaps/google-maps-ios-utils

With 2.4.0 of this library,  we see on the console the following warning: [Unknown process name] CGImageCreate: invalid image alphaInfo: kCGImageAlphaNone. It should be kCGImageAlphaNoneSkipLast

Also CPU and WindowServer starts spiking and it is impossible to use XCode

**Comment by miroslavkovac** [comment]
Hi @seviu, thanks for reporting the issue. This is most likely incompatibility between GoogleMaps rendering engine and Appelium screen recording engine. While we are working on a fix, you may disable the screen recording using:
`AppeliumFeedback.screenRecordingEnabled = false`.

**Comment by seviu** [comment]
Hi @miroslavkovac the crash still happens with screenRecordingEnabled set to false. Just initialising AppeliumFeedback is enough for us to reproduce it.

**Comment by seviu** [comment]
Dos this mean that the screenshot / screen recorder are still active even if we deactivate them?

This is what I am doing in the view controller that renders google maps:

```
- (void)viewDidDisappear:(BOOL)animated
{
	AppeliumFeedback.screenRecordingEnabled = true;
	AppeliumFeedback.screenshotEnabled = true;
	[super viewDidDisappear:animated];
}


- (void)viewWillAppear:(BOOL)animated
{
	AppeliumFeedback.screenRecordingEnabled = false;
	AppeliumFeedback.screenshotEnabled = false;
	[super viewWillAppear:animated];
}
```

Still crashes...

**Comment by miroslavkovac** [comment]
Hi @seviu, the screen recording flag is part of the AppeliumFeedback initialization and is tied to a session. In order to disable it, you would need to do it in for the whole app. The new value will only be applied after you report a bug, so unfortunately you can't disable it per `UIViewController` at the moment. 

We are working on a workaround for GoogleMaps issue and will likely be able to release a new version of `AppeliumFeedback` SDK with this fix later today.

**Comment by miroslavkovac** [comment]
@seviu, we have released version 2.4.4 of AppeliumFeedback. Can you please verify that the crash is fixed? Thanks.

**Comment by seviu** [comment]
Hi @miroslavkovac I can confirm it does not crash

But my console goes crazy with the following message:

```
2020-12-03 17:05:48.205750+0100 homegate.ch[45006:2689058] [Unknown process name] CGImageCreate: invalid image alphaInfo: kCGImageAlphaNone. It should be kCGImageAlphaNoneSkipLast
2020-12-03 17:05:48.495787+0100 homegate.ch[45006:2689058] [Unknown process name] CGImageCreate: invalid image alphaInfo: kCGImageAlphaNone. It should be kCGImageAlphaNoneSkipLast
2020-12-03 17:05:48.790360+0100 homegate.ch[45006:2689058] [Unknown process name] CGImageCreate: invalid image alphaInfo: kCGImageAlphaNone. It should be kCGImageAlphaNoneSkipLast
2020-12-03 17:05:49.083452+0100 homegate.ch[45006:2689058] [Unknown process name] CGImageCreate: invalid image alphaInfo: kCGImageAlphaNone. It should be kCGImageAlphaNoneSkipLast
2020-12-03 17:05:49.379177+0100 homegate.ch[45006:2689058] [Unknown process name] CGImageCreate: invalid image alphaInfo: kCGImageAlphaNone. It should be kCGImageAlphaNoneSkipLast
```

And my WindowServer on the laptop goes to 100%, debugging is almost impossible, and the battery dies super fast.

It is definitely not the ideal scenario, I will have to disable Appelium somehow when debugging, which is not something I really want to do...

**Comment by miroslavkovac** [comment]
Happy to hear that the crash is gone.

The console log seems to be triggered when capturing any UIView which has GoogleMaps subview. Unfortunately, I don't think any fix for that is possible in AppeliumFeedback library. I found an issue reported on [Apple dev forum](https://developer.apple.com/forums/thread/659976) (they don't mention GoogleMaps specifically), but so far it didn't get any attention.

Not sure what exactly could be causing a spike in your WindowServer. For me it is ~8% with screen recording on (while being on a ViewController with a full screen GoogleMaps view) and ~3% with screen recording being off. One thing what you can try is to disable screen recording when the debugger is attached:

`
AppeliumFeedback.screenRecordingEnabled = !AppeliumFeedback.isDebuggerAttached
`

**Comment by seviu** [comment]
Hi @miroslavkovac it does not seem to be related to the screen recorder, I see it even with screen recording disabled.

We will disable Appelium Feedback initialisation when the debugger is attached, and we are not running tests. That should solve it.

Thanks!
