### ISSUE TITLE
'... all-product-headers.yaml' not found

### ISSUE THREAD

**Issue by steven851007** [Appelium/AppeliumFeedback#2]
### Issue
When adding AppeliumFeedback SDK to the project lldb can't compile the project anymore which resulting an error when executing the PO command during debugging:
<img width="749" alt="Screenshot 2022-12-20 at 13 05 03" src="https://user-images.githubusercontent.com/1866462/208595950-ca3af720-64c0-4fda-b2bd-9e2d23883e93.png">

### Expected Results
`po self` -> should output debug information for the shared object.

### Actual Results
`po self` -> Gives an error about missing all-product-headers.yaml for AppeliumFeedbackKit (see screenshot)

### Reason
This is happening due to https://bugs.swift.org/browse/SR-12783. 

> LLDB could clearly do a better job of surfacing the error — I had to dig it out of the types log:
> SwiftASTContext("Instabug")::GetASTContext() – failed to initialize ClangImporter: error: virtual filesystem overlay file '/Users/khaledElMorabea/Library/Developer/Xcode/DerivedData/Instabug-ccnahiryvffhsohhjpovgyeazflu/Build/Intermediates.noindex/ArchiveIntermediates/Instabug/IntermediateBuildFilesPath/Instabug.build/Release-iphonesimulator/Instabug.build/all-product-headers.yaml' not found
> The problem here is with the binary Instabug framework that you are using. The .dSYM files that are generated from Swift code are not (yet) as portable as the ones generated from Clang code. The binary Swift module encode a hardcoded path to a yaml file that only exists on the original developer's machine. You should let them know that they need to compile their binary framework with -no-serialize-debugging-options if they are planning to distribute them to another machine.

See similar issue reported for [Facebook](https://github.com/facebook/facebook-ios-sdk/issues/1628) and [Instabug](https://github.com/Instabug/Instabug-iOS/issues/368)

Solution: Compile the binary framework with -no-serialize-debugging-options.

**Comment by miroslavkovac** [comment]
Thanks for the report and the proposal on addressing the issue. The fix was released in [3.2.2](https://github.com/Appelium/AppeliumFeedback/releases/tag/3.2.2).
